name: Check commands

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check commands
      - uses: actions/checkout@v3
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          stats: true
